### PR TITLE
fix signature of reMock

### PR DESCRIPTION
**Pull request by tamird**
The signature of reMock is the same as mock.

See https://github.com/wheresrhys/fetch-mock/blob/master/src/fetch-mock.js#L343.

### CODE REVIEW

**Comment by tamird** [comment]
@asvetliakov ping

**Comment by asvetliakov** [comment]
@tamird 
Hello, thank you for contribution. Sorry i've been very busy last weeks so i didn't have chance to review.
Regarding typings, i'm waiting for new TS 2.0 npm @types support and i'm planning to push my typings to DT rather than typings repository.

I can merge your PR now (so you can point your typings.json to commit hash), but i don't want to send request to typings registry at least for now. Will it be suitable for you?

**Comment by tamird** [comment]
Sure

**Comment by asvetliakov** [comment]
Ok, thanks!

**Pull request merged**
